#!/bin/sh -e



error()
{
    RET=$?
    MSG=$1
    echo "E: $MSG";
    exit $RET
}

if [ "x$1" = xremove ]; then
    update-alternatives \
        --remove text.plymouth /usr/share/plymouth/themes/biglinux-text/biglinux-text.plymouth  || error "Failed to update-alternatives"

    rm -f /usr/share/plymouth/themes/biglinux-text/biglinux-text.plymouth
fi

exit 0
